title: decidim.time_tracker.default_activity_questionnaire.title
description: decidim.time_tracker.default_activity_questionnaire.description
tos: decidim.time_tracker.default_activity_questionnaire.tos
questions:
  - question_type: single_option
    position: 1
    body: decidim.time_tracker.default_activity_questionnaire.question_1.body
    description: decidim.time_tracker.default_activity_questionnaire.question_1.description
    answer_options:
      - body: decidim.time_tracker.default_activity_questionnaire.question_1.option_1
      - body: decidim.time_tracker.default_activity_questionnaire.question_1.option_2
      - body: decidim.time_tracker.default_activity_questionnaire.question_1.option_3
      - body: decidim.time_tracker.default_activity_questionnaire.question_1.option_4
      - body: decidim.time_tracker.default_activity_questionnaire.question_1.option_5
  - question_type: separator
    position: 2
  - question_type: single_option
    position: 3
    body: decidim.time_tracker.default_activity_questionnaire.question_2.body
    description: decidim.time_tracker.default_activity_questionnaire.question_2.description
    answer_options:
      - body: decidim.time_tracker.default_activity_questionnaire.question_2.option_1
      - body: decidim.time_tracker.default_activity_questionnaire.question_2.option_2
      - body: decidim.time_tracker.default_activity_questionnaire.question_2.option_3
      - body: decidim.time_tracker.default_activity_questionnaire.question_2.option_4
        free_text: true