name: Build

on:
  push:
  pull_request:

env:
  RUBY_VERSION: 2.6.6

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Bundle install
        run: |
          gem install bundler:2.1.4
          bundle install --jobs 4 --retry 3

      - name: Lint and Rubocop
        run: |
          bundle exec rubocop
          bundle exec erblint app/{cells,views}/**/*.erb

      - name: Setup Database
        run: bundle exec rake test_app
    
      # - name: Setup Code Climate test-reporter
      #   run: |
      #     curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      #     chmod +x ./cc-test-reporter
      #     ./cc-test-reporter before-build

      - name: Run RSpec
        run: SIMPLECOV=1 CODECOV=1 bundle exec rake
    
      # - name: Publish code coverage
      #   run: |
      #     export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
      #     ./cc-test-reporter after-build -r "$CC_TEST_REPORTER_ID"
      #   env:
      #     CC_TEST_REPORTER_ID: f4e29abf77907a77f577de201af7791c8f202265a63c09535551146810780eb3