name: Unit Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  RUBY_VERSION: 3.2.6
  NODE_VERSION: 18.17.1

jobs:
  unit:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - run: |
          sudo apt install imagemagick

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install JS dependencies
        run: npm ci

      - name: Setup Database
        run: bundle exec rake test_app

      - run: RAILS_ENV=test bundle exec rails assets:precompile
        name: Precompile assets
        working-directory: ./spec/decidim_dummy_app/

      - name: Run RSpec
        run: CI=1 bundle exec rspec --exclude-pattern 'spec/system/**/*_spec.rb'
